{% set version = "1.1.4" %}
{% set name = "log4cpp" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}-1.1.x%20%28new%29/{{ name }}-1.1/{{ name }}-{{ version }}.tar.gz
  sha256: 696113659e426540625274a8b251052cc04306d8ee5c42a0c7639f39ca90c9d6
  patches:
    - osx_remove_manual_test.patch  # [osx]
    - 0001-cmake-Modify-to-make-shared-library-build-possible.patch

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/index.php?view=timeline&l=log4cpp
    - {{ pin_subpackage('log4cpp', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - autoconf  # [unix]
    - cmake  # [win]
    - ninja  # [win]

test:
  commands:
    - test -f "${PREFIX}/include/log4cpp/Category.hh"  # [unix]
    - test ! -f "${PREFIX}/lib/liblog4cpp.a"  # [unix]
    - test -f "${PREFIX}/lib/liblog4cpp${SHLIB_EXT}"  # [unix]
    - if not exist %PREFIX%\\Library\\include\\log4cpp\\Category.hh exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\log4cpp.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\log4cpp.lib exit 1  # [win]
    - log4cpp-config --help  # [not win]

about:
  home: http://log4cpp.sourceforge.net
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: Log4cpp is library of C++ classes for flexible logging to files
  description: |
    Log4cpp is library of C++ classes for flexible logging to files, syslog,
    IDSA and other destinations. It is modeled after the Log4j Java library,
    staying as close to their API as is reasonable.
  doc_url: http://log4cpp.sourceforge.net/api/index.html
  dev_url: https://github.com/orocos-toolchain/log4cpp

extra:
  recipe-maintainers:
    - marcelotrevisani
    - ryanvolz
