appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: InwDMWbSiXLilp9V9+YzkNe1+TVg5MNB6By1ANdkIU6YZDx55fk1IXgATOHhNR++wbCVhXZo46FbQlYoOYAb7VAx5X7R4IbiGaqBMkciJ9+v9eBSECg/QAuTgLOTAIUekT4SgRPqkxy3Dtrjwg057hPr9bgKARLU6vbwS/xUTWBkMR7niLF8iNVcid7osf0VZb77pf2iC++0k/0fxgm8bPN5xBYfUqYOmSsJYwr5AuuKplhqGA5EGaql2XZO6fVBmVwXNVa9pv1mnUYa2RkyNlqqLObwLEyUmehN5ad4/Fuwu1rLXx/oaan3Vjn3dC7ugKLyhf7Nzz0Whj00YKfyck21VE+CToFr5eotkB5+G38uwKJtHBHqdvgNlJVfLWBVkLWW8FTM+4lcZP8y/a9o6dSIwJSgyfpbpDJomv0y/ICHiGyYq6J+3HnOCzOVcNz4RDmWAKT2at/dP0ZP7NaONTuTMGyvaz+fw71o5RVK7yj20zR/gpdDvk6VwA5t2Y4reNKohr6GTVGK9HYChtsZzHXNMh4XxcSTKsQqwEAgZc5moZ6gs45ln7/20uRw7I3rv50OkeuK+gW9OJHPdeGjN05+wipRpUmCoGK/VHQXpTE+vVfZgMIj2Rl+g9uUmh1zxi5zz7x5q4O5eyGiDgd6mktpNe6qZOwfs2TJKXUnLqo=}
