travis:
  secure:
    BINSTAR_TOKEN: s9Mf7oTBchYSDzE5++tNcIONtQgNiGInGrwi8UxkFN+ee+ljIrrcHIj0dsE+sW5yEiR1zd/Va1fx3SwrQXAMrYRXVentmJSoQo+391TGzj1YU1VGU1/KHHLHXi4v3O8JiFIqTjvlr7qITPtwxTmFad7Ds88NmGJE3LH15hdnycbyBHKonAOj+CSsGbh4TISyQ+MPOLkn0uVhEyZukG3g/e0Y0liIgdMHLeUDLhSM4hySdMDs0SXVXEzJQxkR3y7wizDYS0WS7Rflo5KGtdOdvP8v9E7qlOTK6UQBgFXyqoU/GAEt7k8LT3u/CYgRT8jbSIYoMph3UjcfwL4xVT/0AghChnzL4puQ0XheERsJ6RReN1iALrRdPru3jaM+xA37O1aMx7IrPPQpaqqQK+IYyhShu9kDhDm2DvNeS5IizvhkmarY6v5qquCdze8peyjKIVL5ePOPerSepJlnJhJWAZAZ2Ih3aWpZucMU4LGwmnOzJ/doO0UJ4WYzFPzjb325Ft1VGFDqbIecVvVf2Bw7yMH/rJSwqgRRsC3KyB1YUyMeYwT7efEHfvXrBaEm0Yz0eYzwOXDWqjSLO1nocRWVunc7HOfDZlw37Z9dqJ7d7zwfB9bwa5uUV0NbIcE7z5YDbsx9m/HpvYUOgLLuByOUZ/5CIceehxetA5b4PyaLg6U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
